name: nexi_payment
description: Flutter plugin for Nexi Payment integration (XPay). Supports Web View payment
version: 1.1.1
homepage: https://github.com/PaoloGi/nexi_payment

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.paologi.nexi_payment
        pluginClass: NexiPaymentPlugin
      ios:
        pluginClass: NexiPaymentPlugin

