name: nexi_payment
description: Flutter plugin for Nexi Payment integration (XPay). Supports Web View payment
version: 1.2.0
homepage: https://github.com/PaoloGi/nexi_payment

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.paologi.nexi_payment
        pluginClass: NexiPaymentPlugin
      ios:
        pluginClass: NexiPaymentPlugin

